<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <RootNamespace>Fem2DFluid</RootNamespace>
    <AssemblyName>Fem2DFluid</AssemblyName>
    <ApplicationIcon></ApplicationIcon>
    <StartupObject>Fem2DFluid.Program</StartupObject>
    <BaseOutputPath>C:\Yohoo\FEM2D\bin\</BaseOutputPath>
    <IntermediateOutputPath>C:\Yohoo\FEM2D\obj\</IntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="netDxf" Version="2023.11.10" />
  </ItemGroup>
</Project>
